### ISSUE TITLE
Every few days have to enter credentials

### ISSUE THREAD

**Issue by alexebner** [iMicknl/ha-tahoma#654] opened 2021-11-09 18:46 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

All is working fine but every few days it stops working. Then the integration have e red box with "reconfigure". There i have to enter my somfy credentials. When i have entered it then come a massage with "aborted" and all works again

### What version of this integration (ha-tahoma) has the issue?

2.9.3

### What version of Home Assistant Core has the issue?

core-2021.11.1

### Which gateway / hub do you use?

Somfy Tahoma

**Comment by iMicknl** [comment] 2021-11-10 00:16
Duplicate of https://github.com/iMicknl/ha-tahoma/issues/599. Please continue the conversation there.

**Closed by iMicknl** 2021-11-10 00:16 UTC
Labels: bug
