### ISSUE TITLE
Warnings in log about device_state_attributes

### ISSUE THREAD

**Issue by TheFes** [iMicknl/ha-tahoma#673] opened 2021-12-11 19:03 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I'm getting warnings like this in my log:
`Entity cover.slaapkamer_links (<class 'custom_components.tahoma.cover_devices.awning.Awning'>) implements device_state_attributes. Please report it to the custom component author.`

### What version of this integration (ha-tahoma) has the issue?

2.9.4

### What version of Home Assistant Core has the issue?

core-2021.12.0b7

### Which gateway / hub do you use?

Somfy Conexxoon

### Home Assistant log

```shell
See above
```

**Comment by tetienne** [comment] 2021-12-11 19:29
Hi, this is a duplicate of https://github.com/iMicknl/ha-tahoma/issues/661.

**Closed** 2021-12-11 19:29 UTC
Labels: bug
