### ISSUE TITLE
Reversed state on cover

### ISSUE THREAD

**Issue by sergiojus** [iMicknl/ha-tahoma#350] opened 2021-01-17 18:14 UTC
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
I have 5 identical shutters and only 2 shutters do not go back to right state on Home assistant.

**Expected behavior**
I would like that home assistant give me the right state.

**Screenshots**
All my shutters are closed but in the screenshot, you can see that the "Volet Buanderie" and "Volet Palier" are opened. All my shutters are exactly the same, so I don't undertand why only those two shutters do not have the good state.
![Tahoma1](https://user-images.githubusercontent.com/53393355/104851706-f5903580-58f6-11eb-920f-257c1769b6a9.png)

![tahoma](https://user-images.githubusercontent.com/53393355/104851507-abf31b00-58f5-11eb-9d46-2a589835ab1f.jpg)

**Environment (please complete the following information):**

- ha-tahoma version:2.4.1
- Home Assistant version: Home Assistant 2021.1.4
- Platform: cover

**Device:** (if your problem is related to a specific device)

- **Model**: 
Ui class RollerShutter
Widget PositionableTiltedRollerShutter
Controllable name io:RollerShutterVeluxIOComponent

**Additional context**

**Comment by iMicknl** [comment] 2021-01-17 19:39
Thanks for reporting. This is weird behavior indeed.. Could you share the states (or a screenshot) of the cover that shows the right behavior and one of a cover that shows the wrong behavior?

How does this show on tahomalink.com / the mobile app? I am afraid that this is not an issue in our integration, but rather in the state we retrieve from the tahomalink.com API. Especially since the action buttons are not reversed on your screenshot.

**Comment by sergiojus** [comment] 2021-01-17 20:31
Here is the screenshot of  shutter state in home assistant
![tahoma2](https://user-images.githubusercontent.com/53393355/104854989-4cebd100-590a-11eb-8654-b8e8e91fa914.JPG)

Here is the screenshot of my appmobile
![AppTahoma](https://user-images.githubusercontent.com/53393355/104855002-5ecd7400-590a-11eb-8905-48d57ab4fca0.jpg)

Here is the screenshot of tahomalink
![tahomalink](https://user-images.githubusercontent.com/53393355/104855047-b835a300-590a-11eb-94cb-9c68e414f863.JPG)

thank you in advance

**Comment by iMicknl** [comment] 2021-01-19 19:35
It seems that there is an issue in the latest version of ha-tahoma or changes have been made on the side of Somfy TaHoma... 

We have had these issues in the past as well, however when we reverse the state, someone else will have issues with exactly the same device. We need to investigate more, will let you know when I do require more details.

What is the type (TaHoma vs Connexoon) of your hub and the firmware version of your hub? 

(possible duplicate of #352 and #351)

**Comment by sergiojus** [comment] 2021-01-19 20:02
My box is the tahoma and the firmware version is 3.17.1(324)

**Comment by Steve3581** [comment] 2021-01-22 15:30
I have the exact same issue. It started a few months ago, well before Somfys Tahoma update for native homekit support, I can confirm even there official Apple Homekit awning has the same issue with the states being reversed. (firmware 2020.6.4)

**Comment by Steve3581** [comment] 2021-01-22 15:39
![image](https://user-images.githubusercontent.com/77845375/105511166-e7b02b00-5ccf-11eb-9d7c-b0d4ba88003f.png)

**Comment by Steve3581** [comment] 2021-01-22 15:43
![IMG_0334](https://user-images.githubusercontent.com/77845375/105512042-e9c6b980-5cd0-11eb-9d11-6e7471ead91d.PNG)
![IMG_0335](https://user-images.githubusercontent.com/77845375/105512048-eb907d00-5cd0-11eb-97e5-d15676ab27f6.PNG)

**Comment by iMicknl** [comment] 2021-02-11 23:15
@sergiojus is this issue still present? Please update to the latest version of the integration (2.4.7) and reboot your TaHoma hub.

@Steve3581 could you please share your device states here? You can pull them from `/developer-tools/state`. 

It looks like a bug on the Somfy side, since they report `OpenClosedState` as open instead of closed. See screenshot of @sergiojus in the first post. It is possible that the tahomalink ui looks for the position integer as well, however this should not be necessary...

**Comment by Steve3581** [comment] 2021-02-12 15:23
Hello

I agree its on the Somfy side, that said their update to the Tahoma box last week seems to have fixed the issue on their native homekit support in my case.

**Comment by sergiojus** [comment] 2021-02-13 13:51
I update to the latest version of the integration (2.4.7) and reboot your TaHoma hub. The problem is still present.
I also uninstalled the integration hacs and the integration HA, I reboot HA and reboot TahomaHub. I resinstalled the integration hacs, I reboot HA, and I installed the integration HA. 
But The problem is still present

**Closed** 2021-03-28 01:50 UTC
Labels: bug, bug: reversed state, no-issue-activity

**Comment by iMicknl** [comment] 2021-04-13 20:14
@sergiojus, @Steve3581, is this issue still present?

I would like to see if I can tackle this issue this week. Is anyone willing to work with me via Discord to see if we can debug / fix this issue? Would be great to have this solved before the integration is added to core.

Join us on Discord (https://discord.gg/3Wpn6q9z or add iMick#1903, to discuss in more detail. Eventually the easiest would be if you are able to change your password temporarily and share your credentials privately, so I can have a quick look and see how to fix it :).

**Comment by spacekiek** [comment] 2021-05-07 14:05
Hi,

I've have 2 shutters on my roof who report the open/closed state in reverse. Is there a fix to manually flip the state until Somfy fixes it ?

**Comment by tetienne** [comment] 2021-05-07 14:13
@spacekiek Can you please give more information on yours shutters?

**Comment by tetienne** [comment] 2021-05-07 19:44
@spacekiek I own the same device. This is motor for awning. So _open_ means _deploy_ and _close_ means _undeploy_. If you use it as a cover you observe a reverse state but that's not a bug. 
You can define a cover template to see the state you expect: https://www.home-assistant.io/integrations/cover.template/

**Comment by tetienne** [comment] 2021-05-09 20:38
You can do something like this. So you can use it also in your automation.
```
cover:
  - platform: template
    covers:
      my_cover:
        friendly_name: "My cover"
        value_template: "{{ states(cover.your_cover')|float > 0 }}"
        open_cover:
          - service: cover.close
            target:
              entity_id: cover.your_cover
        close_cover:
          - service: cover.open
            target:
              entity_id: cover.your_cover
        ...
```
