### ISSUE TITLE
Somfy Tahoma invalid auth

### ISSUE THREAD

**Issue by HFeenstra** [iMicknl/ha-tahoma#420] opened 2021-04-15 19:26 UTC
Hello, I had Somfy Tahoma as an integration working, until 2 days ago, April 13th 2021.
HA prompt me to add/retype the password, so I did, but mismatch password…?..

So I opened the Somfy Tahoma app, useless piece of work but ok; password in there worked fine.
Back to Somfy Tahoma integration in HA, no success. Finally deleted the whole Somfy Tahoma integration, rebooted HA but now I can not even add Somfy Tahoma or Somfy integration anymore.
Somfy Tahoma integration prompts me the password in invalid auth. (Even after changing my password in Somfy)
Somfy integration does not work, it prompts me there is already 1 Somfy integration; which I can’t(!) find. So it’s not there, not even in config.yaml file.

So I changed the Somfy password again, still no luck. Can someone point me in the right direction, it worked fine for 3 months… very odd.

Checked the breaking items in 2021.4 and .3 but could not find any related to the Somfy thusfar.

%key:common::config_flow::error::invalid_auth% Is the error when adding the credentials. While testing the tahomalink.com website the credentials are working fine!

**Comment by iMicknl** [comment] 2021-04-16 10:08
Duplicate of https://github.com/iMicknl/ha-tahoma/issues/278.

They did some updates to the service a few days ago, which could maybe result in this behavior. Currenlty we try again very often when we receive a Bad Credentials, which could perhaps result in a temporary ban. This is something that is on our list, but bandwidth is limited unfortunately.

My advice would be to just wait a few days, than add the Somfy TaHoma integration and see if it works. Did you try to login on tahomalink.com via the same IP?

**Comment by Rschack** [comment] 2021-04-16 13:25
Same here, I can login with somfy-connect.com , but not on tahomalink . 
Stopped working a few days ago.

**Comment by HFeenstra** [comment] 2021-04-16 21:18
@iMicknl thank you for your reply. I already changed my password several times, signed in on various apps and tablets all working fine. Just the integration was falling. 
Glad to hear it sounds familiar. Will wait a few days. Hopefully others will comment once it’s working against has an update

**Comment by iMicknl** [comment] 2021-04-16 21:21
@HFeenstra did you remove the integration for a while? It seems that your IP / session has been blacklisted and it could take some time to have this removed.

Changing your password won't help though.

**Comment by HFeenstra** [comment] 2021-04-17 08:25
@iMicknl Thanks, dank ;)

I will try your tip. So will remove the integration as a whole, also in the HACS interface.
Then I will let it sit for a while, 24-48 hours? Any experience with it in the past?

(The integration was already removed, so just the HACS Integration has been removed) Rebooted HA afterwards, will let it sit for a while.

Will be continued...

**Comment by iMicknl** [comment] 2021-04-18 14:15
You don't need to remove the integration files, just make sure it is not added on your Integrations page in HA anymore.

**Comment by HFeenstra** [comment] 2021-04-18 20:54
@iMicknl Thanks I did what you suggested. 
I noticed the new update, so I updated to the latest version, tried again to sign in with the Somfy Tahoma integration. Again no success.
Of course checked the password in the online environment, that is working fine. So the integration is still not running, the integration in HACS is still installed, again with the latest version.

Hop e to hear what can be done next. /thanks

**Comment by iMicknl** [comment] 2021-04-19 10:39
@HFeenstra, @Rschack if you still face issue. Could you send me (via email listed on my profile) your email address? We have been in contact with Somfy about this issue and having your username would help.

**Comment by HFeenstra** [comment] 2021-04-19 15:28
Just send you an email, thanks!

**Comment by sbik38** [comment] 2021-04-19 16:48
Same on my side.
I disabled the integration 3 days ago, but I still cannot login on Tahomalink.com (Login through Phone app works, login through Somfy web site works too).
I just try to update the integration through HACS, and enable again the integration ==> Same result
All my tahoma entities are still "undefined"
Usually when I uninstall the integration  and try to reinstall it, the system reject my password (which is correct 100% sure)
Any idea ?
Should I wait longer than 3 day with that integrayion disabled ?
Thanks

**Comment by iMicknl** [comment] 2021-04-19 16:50
@sbik38 unfortunately we cannot change this. If you send me your email (your login username) to my email (see my profile), I will add it to the email to Somfy.

**Comment by sbik38** [comment] 2021-04-19 20:22
@iMicknl 
email sent !
Thanks

**Comment by sbik38** [comment] 2021-04-20 10:41
seems to be backto normal today !  Tahomlink login is OK again

**Comment by HFeenstra** [comment] 2021-04-22 20:29
Too bad, ever since @sbik38 post the above link I have not been able to sign in. 
Even uninstalled and re installed. 
So I will wait patiently to a more firm solution. Thanks anyway for the help thus far.

**Comment by iMicknl** [comment] 2021-04-22 21:03
@HFeenstra we already got in touch with Somfy and the only thing I can think of, is that you are still hitting the API. Are you sure that you are not calling the API from your IP?

Your account was temporarily banned and this should be resolved if you stop hitting the API for at least 10 minutes. I am not sure why this is still an issue on your side, but otherwise you would need to contact Somfy support probably..

**Comment by HFeenstra** [comment] 2021-04-28 18:42
Hello @iMicknl and others. No idea what happend but after several time trying, removing, adding, password verifying I just got the Tahoma once again connected to the HA environment. 
Odd thing is I haven’t done anything special. Ok I removed a few days ago the browser cache on my cell phone…

So overall its working again, automations were connected again and I tried it. Hopefully it will keep working. 

Thanks for the effort and reply’s this far.

**Comment by iMicknl** [comment] 2021-04-28 20:54
@HFeenstra great to hear! I am not sure what could have caused this behavior. I have improved this behavior in the core pull request, will try to backport it to this integration as well. 

Let's close this issue for now, since we have a similar issue open already.

**Closed by iMicknl** 2021-04-28 20:54 UTC
Labels: blocked, bug
