### ISSUE TITLE
Plugin needs reconfiguration after server maintenance

### ISSUE THREAD

**Issue by mingan666** [iMicknl/ha-tahoma#669] opened 2021-12-09 07:07 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

When the server is down for maintenance, the plugin is disabled and requires reconfiguration.
I do understand the issues that where the reason for introducing the reconfiguration on bad credentials error.
However, I was hoping a work around could be possible to differentiate server maintenance.
In that case it might be possible to simply retry after some timeout (every 1 or 5 or even 15 min)?

When the plugin is disabled, it is only me that can reconfigure it.
The rest of the family just have to wait for me to be able to do it...

### Which gateway / hub do you use?

Tahoma Pro by Somfy Firmware: 2021.4.4

### Additional information

This error originated from a custom integration.

Logger: custom_components.tahoma
Source: helpers/update_coordinator.py:219
Integration: Overkiz (by Somfy)
First occurred: December 7, 2021, 13:32:58 (2 occurrences)
Last logged: December 8, 2021, 12:45:48

Error fetching device events data: Server is down for maintenance.

**Comment by iMicknl** [comment] 2021-12-09 07:40
Duplicate of https://github.com/iMicknl/ha-tahoma/issues/599

**Closed by iMicknl** 2021-12-09 07:40 UTC
Labels: enhancement
