### ISSUE TITLE
[PositionableHorizontalAwning] Commands and state are reversed for vertically mounted covers

### ISSUE THREAD

**Issue by Janthenman67** [iMicknl/ha-tahoma#352] opened 2021-01-18 19:32 UTC
Describe the bug
I have a Somfy screen/cover and it has the reversed state on Home assistant.

Expected behavior
I would like that home assistant give me the right state.

```
current_position: 100
ui_class: Awning
widget: PositionableHorizontalAwning
controllable_name: 'io:HorizontalAwningIOComponent'
rssi_level: 2
'core:NameState': SUNILUS io
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': verylow
'core:RSSILevelState': 2
'core:MovingState': false
'core:DeploymentState': 100
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
'core:TargetClosureState': 100
friendly_name: SUNILUS io
icon: 'hass:garage-variant'
supported_features: 527
device_class: awning
```

Environment (please complete the following information):

ha-tahoma version:2.4.1
Home Assistant version: Home Assistant 2021.1.4

**Comment by iMicknl** [comment] 2021-01-19 19:33
Thanks for reporting @Janthenman67. It seems that there is an issue in the latest version of ha-tahoma or changes have been made on the side of Somfy TaHoma... 

We have had these issues in the past as well, however when we reverse the state, someone else will have issues with exactly the same device. We need to investigate more, will let you know when I do require more details.

Do you know the firmware version of your Connexoon IO box? And just to double check, the status on tahomalink.com is correct?

(possible duplicate of #351 and #350)

**Comment by Janthenman67** [comment] 2021-02-21 17:15
yes, the issue i still present (unfortunately)

**Comment by sneekerzzz** [comment] 2021-03-18 21:30
This is something from the beginning. I was looking for an option to reverse controls but now I found this it explains why.

**Comment by iMicknl** [comment] 2021-03-18 22:05
@sneekerzzz could you perhaps post more details about your devices? (firmware of the hub and the device details of the cover where the state is reversed).

I am willing to reverse the states again, however then we will have created issues by others where the device is reversed... It seems that the apps are able to understand how to reverse it, but we haven't been able to figure out where they look at.

**Comment by iMicknl** [comment] 2021-04-13 11:58
@Janthenman67, @sneekerzzz, I would like to see if I can tackle this issue this week. Is anyone willing to work with me via Discord to see if we can debug / fix this issue? Would be great to have this solved before the integration is added to core.

Join us on Discord (https://discord.gg/3Wpn6q9z or add iMick#1903, to discuss in more detail. Eventually the easiest would be if you are able to change your password temporarily and share your credentials privately, so I can have a quick look and see how to fix it :).

**Comment by iMicknl** [comment] 2021-04-13 20:10
Apparently, both of you (@Janthenman67 / @sneekerzzz) have a vertically mounted cover, but the motor is of the type PositionableHorizontalAwning (`io:HorizontalAwningIOComponent`).

Executing `cover.open()` will close the cover, even though we call the device commands 'up' or 'open'. 

Executing `cover.close()` will open the cover, even though we call the device commands 'down' or 'close'. 

It seems that we are not able to easily fix this, since everything is reversed (not just the state, as with the other issues). I will have a look to see if it is feasible to have an `inverted` option in core.

**Comment by tetienne** [comment] 2021-04-19 10:17
@sneekerzzz @Janthenman67 Any chance you can try this branch: https://github.com/iMicknl/ha-tahoma/pull/427? It should solved your issue.

**Comment by Janthenman67** [comment] 2021-04-19 16:20
I installed the ZIp file and i got this:

![image](https://user-images.githubusercontent.com/69641492/115269756-e7db8d80-a13b-11eb-9d18-09fb9f53f4b2.png)

it's the other way arond (arrows and state as well)

**Comment by Janthenman67** [comment] 2021-04-19 16:23
strange thing, because in the UI it looks like this at the same time
(the switch shows open (its not working anymore tho, and the camera proves it is indeed open)
![image](https://user-images.githubusercontent.com/69641492/115270083-443ead00-a13c-11eb-879e-d3a566d3f5b3.png)

**Comment by sneekerzzz** [comment] 2021-04-19 17:22
Quick screen shot


Op ma 19 apr. 2021 om 18:23 schreef Janthenman67 ***@***.***>:

**Comment by tetienne** [comment] 2021-04-19 21:02
@Janthenman67 did you customize your awning entity? It's well an horizontal device?
Mine looks like this

![image](https://user-images.githubusercontent.com/8216238/115302904-394b4300-a163-11eb-8fea-900ac010a36e.png)

On your camera, I don't understand what I see sorry.

**Comment by Janthenman67** [comment] 2021-04-19 21:10
Mine looks like this. It is closed now (so: down position) No, i didn't customize. It is a screen you were looking at. It is simular o a gragedoor and closes or opens the cabin in the garden. 

![image](https://user-images.githubusercontent.com/69641492/115303571-14a39b00-a164-11eb-8419-954a8819980f.png)

**Comment by tetienne** [comment] 2021-04-20 07:04
@iMicknl Any idea why this awning is returned as a blind? I have the exact same device io:HorizontalAwningIOComponent which is displayed as an awning for me.

**Comment by Janthenman67** [comment] 2021-04-20 07:43
No, I changed the entity to "Blind", because it's not an Awning. I easily can change it back ofc. but the awning switches (in or out) instead of arrow up and down) don't make much sense in my case.
![image](https://user-images.githubusercontent.com/69641492/115357366-db4b4980-a1bc-11eb-8c2d-321e9c91d795.png)

**Comment by iMicknl** [comment] 2021-04-20 07:45
> @iMicknl Any idea why this awning is returned as a blind? I have the exact same device io:HorizontalAwningIOComponent which is displayed as an awning for me.

The device class is changed in the HA interface, but this shouldn't make a difference in terms of functionality.

Both users in this issue have their HorizontalAwning vertically mounted by the way.

**Comment by tetienne** [comment] 2021-04-20 08:08
I think I got it. You are using an awning motor to act like a blind. For an awning, close means the device is collapsed, but for a blind it means uncollapse. So it’s why it behaves in the opposite way for you. 

So I’m curious, within the Tahomalink website, how the device is displayed when collapsed or uncollapsed?

**Comment by Janthenman67** [comment] 2021-04-20 08:37
I'm not even sure I use that site. I'm not using any app either. I only registerred the conexoon once. So I have to check.

**Comment by sneekerzzz** [comment] 2021-04-20 08:51
IT looks like this

**Comment by iMicknl** [comment] 2021-04-20 08:52
@sneekerzzz it seems that your images are not coming through since you replied via email. Could you perhaps upload them via github.com?

**Comment by Janthenman67** [comment] 2021-04-20 14:06
The only thing I ever did was registering the connexoon on the somfy website and chose (because I had to) for the Terrace app. Then I connected the remote that comes with the screent to the Connexoon. I never bothered to download the Terrace app  but went straight to HA and took it from there.

**Comment by iMicknl** [comment] 2021-04-20 14:11
> The only thing I ever did was registering the connexoon on the somfy website and chose (because I had to) for the Terrace app. Then I connected the remote that comes with the screent to the Connexoon. I never bothered to download the Terrace app but went straight to HA and took it from there.

Do you still have the app? It would be good to understand if they are visualizing it reversed as well.. The limits of this integration are at the data we receive from the Somfy API's.

**Comment by Janthenman67** [comment] 2021-04-20 14:13
> > The only thing I ever did was registering the connexoon on the somfy website and chose (because I had to) for the Terrace app. Then I connected the remote that comes with the screent to the Connexoon. I never bothered to download the Terrace app but went straight to HA and took it from there.
> 
> Do you still have the app? It would be good to understand if they are visualizing it reversed as well.. The limits of this integration are at the data we receive from the Somfy API's.

no, but I can download it of course and see how it shows

**Comment by Janthenman67** [comment] 2021-04-20 15:32
Ok, I give up on the app. not possible to login too. The screen only shows for half a second. Those Somfy apps have room for improvement, just saying.

**Closed** 2021-05-26 03:10 UTC
Labels: bug, bug: reversed state, no-issue-activity
