### ISSUE TITLE
Not accepted by home assistant core 2024.11.0

### ISSUE THREAD

**Issue by Egobo2001** [iMicknl/ha-tahoma#857] opened 2024-11-06 23:50 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello , it's seems it's not accepted by Home assistant core 2024.11.0...

### What version of this integration (ha-tahoma) has the issue?

2.15.0

### What version of Home Assistant Core has the issue?

2024.10.4

### Which gateway / hub do you use?

Tahoma V2

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by aarthjo** [comment] 2024-11-07 07:52
Hey !

Please find below the error for me wiht core 2024.11.0. I know that this integration is deprecated but is it possible to update the pyoverkiz lib ?

`> Unable to install package pyoverkiz==1.8.0: × No solution found when resolving dependencies: ╰─▶ Because pyoverkiz==1.8.0 depends on attrs>=21.2,<24.0 and attrs==24.2.0, we can conclude that pyoverkiz==1.8.0 cannot be used. And because you require pyoverkiz==1.8.0, we can conclude that your requirements are unsatisfiable.`

Thanks,

**Comment by cgeroldinger** [comment] 2024-11-07 10:28
Just updated to 2024.11.0 and similar issue now.

**Comment by iMicknl** [comment] 2024-11-07 10:40
Duplicate of #856. This is a known issue indeed and this won't be fixed unfortunately. When we have migrated all entities from this repository, we will archive this repository as well.

You can always try yourself to update pyoverkiz (in the manifest.json), however most likely there are too many breaking changes. The way forward is to use Overkiz in core (even though there is not 100% feature parity yet).

**Closed by iMicknl** 2024-11-07 10:40 UTC
Labels: bug

**Comment by Egobo2001** [comment] 2024-11-09 09:14
Thanks, I understand.
All my zwave components are on Somfy Tahoma, and a lot of scenaries are on it too.
Unfortunately, zwave don't travel to HA with the official Overkiz...And I'm not ready to change Somfy to HA...
HA seems too gadget for my wife, and I don't have enough courage to custom HA for my wife...
I'll stay on HA 2024.10.4 at this moment until I change and configure HA to a friendly and usable out of my house without VPN for my wife...
HA will stay an accessorie for my photovoltaic system at this moment .
Thank you.

**Comment by PvaI** [comment] 2024-11-10 13:23
> The way forward is to use Overkiz in core (even though there is not 100% feature parity yet).

I can't control the device from the core integration, which defeats the purpose of having it in HA. The device is seemingly set to automode and will throw an error when I try to set any other mode. The device will operate independently and start heating any time of day and there is no way to control it.
