### ISSUE TITLE
Need to reauthenticate every 1 or 2 days

### ISSUE THREAD

**Issue by Dathiefnl** [iMicknl/ha-tahoma#698] opened 2022-01-03 13:34 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Every 1 or 2 days i need to reauthenticate the Overkiz intergration. I already fully uninstalled the intergration and reinstalled it but also that does not work. Because of this we get a lot of automation problems here at home.

### What version of this integration (ha-tahoma) has the issue?

2.10.2

### What version of Home Assistant Core has the issue?

core-2021.12.7

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

PositionableRollerShutter

**Comment by BrentVerhaegen** [comment] 2022-01-03 13:39
I have the same issue. I'm following. Has been happening for a few weeks now.
Need to authenticate every few days. 
In my case, once I've done this I get a little pop-up with _Aborted_, but everything works again as it should for a few days, before the same issues pops up again.

**Comment by iMicknl** [comment] 2022-01-03 14:53
Duplicate of https://github.com/iMicknl/ha-tahoma/issues/599. See the pinned issue on this repository.

Explanation: https://github.com/iMicknl/ha-tahoma/issues/599#issuecomment-995825550

**Closed by iMicknl** 2022-01-03 14:53 UTC
Labels: bug
