### ISSUE TITLE
Lost connection all devices

### ISSUE THREAD

**Issue by HFeenstra** [iMicknl/ha-tahoma#713] opened 2022-01-16 04:42 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since  er version 2.11 I can not control the curtains and window. All of Tahoma devices. Have no other devices for Somfy. 

### What version of this integration (ha-tahoma) has the issue?

2.11

### What version of Home Assistant Core has the issue?

2012.12.9

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

Updowndualcurtain

### Home Assistant log

<details><summary>Logs</summary>

```
2022-01-16 10:25:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration samsungtv_tizen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration brandstofprijzen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration battery_consumption which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration afvalinfo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:25:57 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-16 10:26:55 DEBUG (MainThread) [custom_components.tahoma.config_flow] DHCP discovery detected gateway ****-****-4898
2022-01-16 10:26:55 DEBUG (MainThread) [custom_components.tahoma.config_flow] Gateway ****-****-4898 is already configured
```

</details>

**Comment by tetienne** [comment] 2022-01-16 05:43
Please enable the debug logging as explain in the README and update your message.

**Comment by HFeenstra** [comment] 2022-01-16 09:36
Hello @tetienne Thank you so much for the quick reply. I did add the logging information. Let me know if there is still something missing.

**Comment by HFeenstra** [comment] 2022-01-16 09:42
To add to it:
the versions before I was able to control the devices. But now and then I had to reauthenticate the credentials. So I was hoping this new version, 2.11 would solve these issues. Hope you can find the cause of this issue.

**Comment by tetienne** [comment] 2022-01-16 09:50
Look like a duplicate of https://github.com/iMicknl/ha-tahoma/issues/599

**Comment by HFeenstra** [comment] 2022-01-16 09:53
Not completly, in #599 the user stills gets an option every other day/days to re enter the credentials.
Since the upgrade to version 2.11 I do not even get the option to re enter the credentials anymore.

**Comment by iMicknl** [comment] 2022-01-16 10:58
Duplicate of #599.

@HFeenstra unfortunately I lot has been said in #599, thus it is not easy to catch up with. However we temporarily removed the reauth dialog and moved back to a previous implementation, where there is a risk to be temporarily banned.

Please revert to a previous version for now, if you had a better experience before. We will soon come with a hopefully more definitive fix.

**Closed by iMicknl** 2022-01-16 10:58 UTC
Labels: bug
