### ISSUE TITLE
Frequently enter password

### ISSUE THREAD

**Issue by VoetenK** [iMicknl/ha-tahoma#719] opened 2022-01-20 09:10 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I regularly have to re-enter my password. Why is this necessary? Can this be avoided?

### What version of this integration (ha-tahoma) has the issue?

latest

### What version of Home Assistant Core has the issue?

core-2021.12.10

### Which gateway / hub do you use?

Tahoma V2

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Comment by iMicknl** [comment] 2022-01-20 09:17
Duplicate of pinned issue #599

We are currently working on implementing their newer and more stable authentication method.

**Closed by iMicknl** 2022-01-20 09:17 UTC
Labels: bug
