### ISSUE TITLE
Binary sensors do not reflect sensor state

### ISSUE THREAD

**Issue by ReRuBabs** [iMicknl/ha-tahoma#526] opened 2021-08-14 01:51 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since last update the window and motion sensors do not function well. The binary sensor value (on/off) does not reflect the correct values of the core attributes ContactState and OccupancyState.

### What version of this integration (ha-tahoma) has the issue?

2.6.2

### What version of Home Assistant Core has the issue?

core-2021.8.6

### Which gateway / hub do you use?

Tahoma V2 hub

### Device model

ContactSensor / OccupancySensor

### Device type

io:SomfyContactIOSystemSensor / io:SomfyOccupancyIOSystemSensor

**Comment by tetienne** [comment] 2021-08-14 04:34
Hi, thanks for reporting. This is a duplicate of #525.

You can comment it to add your case.

**Closed** 2021-08-14 04:34 UTC
Labels: bug

**Comment by iMicknl** [comment] 2021-08-15 09:48
Fixed in v2.6.3!
