### ISSUE TITLE
Add support for Modulis Heater (rts:ExteriorHeatingRTSComponent)

### ISSUE THREAD

**Issue by larsvinc** [iMicknl/ha-tahoma#211] opened 2020-08-07 21:05 UTC
**Device information**
The device is a terrasse heater:
https://www.somfy.me/en-gc/products/1810876/heating-modulis-ramp-rts-

It uses the same buttons as my blinds:
- "up"/"on" (on for the heater)
- "down"/"off" (off for the heater)
- "my" Programmable setting for the heater

If it exposes more functions through the API that would be great to have them supported (such as selecting the heating level).

**Device details**

**Comment by vlebourl** [comment] 2020-08-08 05:15
```
2020-08-06 18:22:01 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rts:ExteriorHeatingRTSComponent - ExteriorHeatingSystem - StatelessExteriorHeating)
```

**Comment by iMicknl** [comment] 2020-08-10 07:00
```
{
	"commands": [{
		"commandName": "down",
		"nparams": 0
	}, {
		"commandName": "identify",
		"nparams": 0
	}, {
		"commandName": "my",
		"nparams": 0
	}, {
		"commandName": "off",
		"nparams": 0
	}, {
		"commandName": "on",
		"nparams": 0
	}, {
		"commandName": "onWithTimer",
		"nparams": 1
	}, {
		"commandName": "rest",
		"nparams": 0
	}, {
		"commandName": "stop",
		"nparams": 0
	}, {
		"commandName": "test",
		"nparams": 0
	}, {
		"commandName": "up",
		"nparams": 0
	}],
	"states": [],
	"dataProperties": [{
		"value": "0",
		"qualifiedName": "core:identifyInterval"
	}],
	"widgetName": "StatelessExteriorHeating",
	"uiClass": "ExteriorHeatingSystem",
	"qualifiedName": "rts:ExteriorHeatingRTSComponent",
	"type": "ACTUATOR"
}
```

**Comment by larsvinc** [comment] 2020-08-10 07:05
Some comments regarding wanted functionality:
- I suspect that "up" and "down" differs from "on" and "off". It is possible to adjust the heating with "up" and "down" after the unit is turned on. So it would make sense to enable all those. 
- "my" sets the heating at a pre-programmed level
- As for "rest" and "stop", I have no idea what they do. Is it possible for me to test the full API and report back what the commands do?

**Comment by iMicknl** [comment] 2020-08-10 07:33
@vlebourl do you think it is possible to map this one to the `climate` platform as well? 

@larsvinc if you are somewhat familiar with Python, I could help you test out those commands manually. However, sometimes there are some commands that are not working or mapped to the same behaviour as others.

**Comment by larsvinc** [comment] 2020-08-10 12:31
@iMicknl : I am fairly familiar with python (I have for instance committed code into HA), so I would be happy to test the commands. 
'
Regarding choice of platform, the climate as I know it might not be that suitable since there is no thermostat, and it is stateless?

**Comment by iMicknl** [comment] 2020-08-12 09:06
@larsvinc not sure, @vlebourl is our climate integration man 😃. 

I am still figuring out the best way for you to test those other commands. You could directly use the https://github.com/imicknl/python-tahoma-api, however it requires a bit more efforts. You would first need to capture your device url and than pass it via a command, like we do in this integration.

https://github.com/iMicknl/ha-tahoma/blob/4e6caa6df332f451e084747f58d49e02b5084435/custom_components/tahoma/tahoma_device.py#L153-L157

**Comment by vlebourl** [comment] 2020-08-12 13:03
Hi, sorry guys I'm not very responsive, currently on well deserved holidays (first in two years...). Lacking the thermostat is not a problem. That's The same as for 2 of our supported climate platforms. If we map this device to a climate entity, the available commands will be turn on and off, set temperature, which doesn't make much sense here I guess, and set preset modes. I'm not sure how we could map the up/down to anything in a climate device as increasing and decreasing the hearing level is not the same as setting a predefined temperature...

**Comment by iMicknl** [comment] 2020-08-12 13:10
@vlebourl enjoy your vacation!! ⛱️ Take some well deserved downtime as well.

**Comment by larsvinc** [comment] 2020-08-18 20:49
Agree with @iMicknl  , enjoy the vacation.

I will try to test that, but I have to admit that this was a highly non-trivial way to access the device. Can I append the commands to the example script on the front page of python-tahoma-api? It lists all the devices, but that might just be strings (and not objects)?

Some wild and dirty proposals on my end, would it be feasible to have temp = 1,2,3 and use up/down to get there (i.e. press "up" once to go from 2->3? The issue is of course then the "temp" does not map to the real state of the device.

**Comment by vlebourl** [comment] 2020-08-18 21:06
The issue is not that temp is not the real state, but rather that I'm not sure how to map increase/decrease. The command in the code is set_temperature, not increase our decrease temperature... Not sure yet if I can overcome this.

**Comment by vlebourl** [comment] 2020-08-18 21:08
How many levels do you have? If it's only 3, we could map them to presets instead of temperature

**Comment by larsvinc** [comment] 2020-08-18 21:13
There are 3 levels (call them low, med, full for simplicity). Switching can only be done via up/down as far as I know. And the startup is programmable. Likewise "my" is a programmable level (I have mine at medium).

**Comment by vlebourl** [comment] 2020-08-19 04:45
With only 3 levels and no concept of temperature, I think the easiest is to have presets. Then there aren't too many cases to code. Going from 1 to 3 for instance will be done with 2 ups, and so on.

**Comment by vlebourl** [comment] 2020-08-31 07:18
Hi, sorry for the long silence. I'm looking at that device now, and using presets isn't a very convincing solution. As this is a stateless device, I have no way of knowing what's the state and hence how many ups and downs to apply to go from one preset to another. I don't have any way to know whether it's on or off either... I would suggest having on/off capability only as those commands are straightforward and don't depend on the state. But only register "up", "down" and "my" services instead of preset support. Would that be good enough for you?

**Comment by larsvinc** [comment] 2020-08-31 15:15
Hi,

Up / Down / My sounds good to me. Does that mean that it becomes a climate device?

**Comment by vlebourl** [comment] 2020-08-31 15:17
It would be a climate device indeed. If you have other ideas on what to map it too, I'm all ears! 
Otherwise, you can try this branch: https://github.com/iMicknl/ha-tahoma/tree/feature/support_exterior_modulis_heater_211 where there's a first implementation of your device as a climate entity with on/off accessible in the ui and up/down/my as services.

**Comment by larsvinc** [comment] 2020-08-31 15:23
Will do!

It is feasible to get to a known state by turning the device on and off. But that known state would depend on what the user programmed as the default. So long story short, that would be a dirty fix, and would depend on each installation. So I think it should be avoided.

Bottom line: No better suggestions here :+1:

**Comment by vlebourl** [comment] 2020-08-31 15:25
That wouldn't really be a known state in the sense that even thought the user knows the state the device starts in, TaHoma doesn't return any state (as for any RTS device) that can be used in the implementation, hence the widget name "StatelessExteriorHeating".

**Comment by larsvinc** [comment] 2020-08-31 15:33
I fully agree with you.

Tested the branch. It did not detect the heater:
2020-08-31 17:32:14 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rts:ExteriorHeatingRTSComponent - ExteriorHeatingSystem - StatelessExteriorHeating)

I do see the climate_seh.py in the custom components folder. Am I missing something? Do I need to do something beyond restarting HA?

**Comment by vlebourl** [comment] 2020-08-31 15:35
Nope, I forgot to add it to the supported types, my bad... Should be detected now.

**Comment by vlebourl** [comment] 2020-08-31 15:38
Do you know whether the device cycles through the levels if you hit up multiple times? If not, we could have the 3 levels as presets and select the correct level by doing enough ups or downs to reach a guaranteed known states:
-> 2 ups => level 3
-> 2 downs => level 1
-> 2 ups 1 down => level 2
my command would still be a service only as the 3 levels would be directly accessible.

**Comment by vlebourl** [comment] 2020-08-31 15:41
Would you rather have sleep/eco/comfort or eco/comfort/boost?

**Comment by vlebourl** [comment] 2020-08-31 15:48
new commit to the branch with the presets.

**Comment by larsvinc** [comment] 2020-08-31 15:59
Hi,

It does not cycle. So the presets work. I would propose eco/comfort/boost! 

On a note "sleep" proposes that you can have it there while not using it, but it uses a lot of power, so that is something one should not do (or does it suggest to sleep under it? :P)

It is detected as a device, but without any entities now.

**Comment by vlebourl** [comment] 2020-08-31 16:14
Just pushed a fix.

**Comment by vlebourl** [comment] 2020-08-31 16:27
Yet other fixes, can you verify through the dev page that the my service is working?

**Comment by larsvinc** [comment] 2020-08-31 16:43
Invalid config
The following integrations and platforms could not be set up:

tahoma.climate
Please check your config.

Nothing in the log. Configured via GUI.

**Comment by larsvinc** [comment] 2020-08-31 16:43
The entity still does not show up

**Comment by vlebourl** [comment] 2020-08-31 18:36
don't understand, it works on my side on a vanilla install. I'll have a better look tomorrow...

**Comment by larsvinc** [comment] 2020-08-31 19:09
I reinstalled the integration to try once more.

I keep getting the device, but no entities:
![image](https://user-images.githubusercontent.com/16321939/91756983-f5083400-ebcd-11ea-8c18-e905ff244cf8.png)

![image](https://user-images.githubusercontent.com/16321939/91757095-1bc66a80-ebce-11ea-8b90-9664595090d5.png)

Let me know if there is something I can do to help debugging.

**Comment by vlebourl** [comment] 2020-08-31 19:22
Very strange... No further message in the log?

**Comment by larsvinc** [comment] 2020-08-31 19:46
Nope

**Comment by vlebourl** [comment] 2020-09-01 06:30
Hey back, I added some debug logging, can you test and report on the last version? Thanks

**Comment by larsvinc** [comment] 2020-09-01 11:01
Hi,

I have done a new pull, and same situation. Some more debug though:
2020-09-01 12:58:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.052 seconds
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:31 DEBUG (MainThread) [custom_components.tahoma.tahoma_device] Init Tahoma Device
2020-09-01 12:58:41 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.179 seconds
2020-09-01 12:58:51 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.163 seconds
2020-09-01 12:59:01 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.169 seconds
2020-09-01 12:59:11 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.175 seconds

**Closed** 2020-09-04 09:38 UTC
Labels: new-device, platform: climate
