### ISSUE TITLE
WARNING: device_state_attributes 

### ISSUE THREAD

**Issue by antivirus68** [iMicknl/ha-tahoma#674] opened 2021-12-12 10:01 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I've just updated HA to 2021.12.0 and I got Tahoma v2.9.4.

The HA log reports:

2021-12-12 10:38:20 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.

I think there is a change that needs to be addressed.

Thanks

### What version of this integration (ha-tahoma) has the issue?

2.9.4

### What version of Home Assistant Core has the issue?

2021.12.0

### Which gateway / hub do you use?

Somfy Tahoma

### Home Assistant log

```shell
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-12 10:53:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity cover.xxxxxxxxxx (<class 'custom_components.tahoma.cover_devices.vertical_cover.VerticalCover'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by iMicknl** [comment] 2021-12-12 10:56
Thanks for reporting. This is a duplicate of #661.

If you use the latest master version, this warning will be gone. Or wait for the upcoming release of the integration.

**Closed** 2021-12-12 10:57 UTC
Labels: bug

**Comment by antivirus68** [comment] 2021-12-12 15:29
Thanks. I just got the update.
