### ISSUE TITLE
Failed to set up /  __init__() missing 1 required keyword-only argument: 'last_update_time'

### ISSUE THREAD

**Issue by hdejongh** [iMicknl/ha-tahoma#714] opened 2022-01-16 07:44 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

the integration fails to setup, debug logs show the following error message

ERROR (MainThread) [custom_components.tahoma] __init__() missing 1 required keyword-only argument: 'last_update_time'

### What version of this integration (ha-tahoma) has the issue?

2.11.0

### What version of Home Assistant Core has the issue?

core-2021.12.9

### Which gateway / hub do you use?

somfy tahoma

### Device model

rolluiken!

### Home Assistant log

<details><summary>Logs</summary>

```
ERROR (MainThread) [custom_components.tahoma] __init__() missing 1 required keyword-only argument: 'last_update_time'
Traceback (most recent call last):
File "/config/custom_components/tahoma/__init__.py", line 64, in async_setup_entry
setup, scenarios = await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 261, in get_setup
setup = Setup(**humps.decamelize(response))
TypeError: __init__() missing 1 required keyword-only argument: 'last_update_time'
```

</details>

**Comment by tetienne** [comment] 2022-01-16 09:20
Hi, thank you for reporting. Your issue is a duplicate of https://github.com/iMicknl/ha-tahoma/issues/706

**Closed** 2022-01-16 09:20 UTC
Labels: bug
