### ISSUE TITLE
io:HorizontalAwningIOComponent is locked and does not respond to commands

### ISSUE THREAD

**Issue by cdeharo** [iMicknl/ha-tahoma#319] opened 2020-12-06 11:47 UTC
**Describe the bug**
The awning reports in state locked and does not respond to open, close or set position.

**To Reproduce**

1. Call the `cover.open_cover`, `cover.close_cover` or `cover.set_cover_position` services against the awning
2. Observe that the awning does not respond to the service calls

**Expected behavior**
The awning respond to the service calls.

**Environment (please complete the following information):**

- **ha-tahoma version:** 2.3.7
- **Home Assistant version:** 0.118.5
- **Platform**: cover

**Device:**

- **Model**: PositionableHorizontalAwning by Somfy
- **Type**: io:HorizontalAwningIOComponent

**Additional context**

I've checked that before updating to 2.3.7 the awning is working without problems.

Below are the logs registered when trying to open the awning:
```
2020-12-06 12:39:12 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.EXECUTION_REGISTERED/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: None, state: None -> None)
2020-12-06 12:39:12 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.EXECUTION_STATE_CHANGED/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: None, state: ExecutionState.INITIALIZED -> ExecutionState.NOT_TRANSMITTED)
2020-12-06 12:39:12 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.GATEWAY_SYNCHRONIZATION_STARTED/None (device: None, state: None -> None)
2020-12-06 12:39:12 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.EXECUTION_STATE_CHANGED/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: None, state: ExecutionState.NOT_TRANSMITTED -> ExecutionState.TRANSMITTED)
2020-12-06 12:39:12 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.042 seconds
2020-12-06 12:39:13 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.GATEWAY_SYNCHRONIZATION_ENDED/None (device: None, state: None -> None)
2020-12-06 12:39:13 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.084 seconds
2020-12-06 12:39:14 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.DEVICE_STATE_CHANGED/None (device: io://0816-7496-2665/5381185, state: None -> None)
2020-12-06 12:39:14 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.EXECUTION_STATE_CHANGED/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: None, state: ExecutionState.TRANSMITTED -> ExecutionState.IN_PROGRESS)
2020-12-06 12:39:14 DEBUG (MainThread) [custom_components.tahoma.coordinator] CommandExecutionStateChangedEvent/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: io://0816-7496-2665/5381185, state: None -> ExecutionState.FAILED)
2020-12-06 12:39:14 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.EXECUTION_STATE_CHANGED/37d93c39-ac10-3e01-2cbc-39a6dadb77f6 (device: None, state: ExecutionState.IN_PROGRESS -> ExecutionState.FAILED)
2020-12-06 12:39:14 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.040 seconds
```

Below are the device attributes:
```yaml
current_position: 0
ui_class: Awning
widget: PositionableHorizontalAwning
controllable_name: 'io:HorizontalAwningIOComponent'
rssi_level: 88
'core:NameState': Toldo salon
'io:PriorityLockOriginatorState': wind
'core:PriorityLockTimerState': 870
'io:PriorityLockLevelState': comfortLevel1
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 88
'core:DeploymentState': 0
'core:OpenClosedState': closed
'core:TargetClosureState': 0
friendly_name: Toldo salon
icon: 'mdi:weather-windy'
supported_features: 527
device_class: awning
```

**Comment by cdeharo** [comment] 2020-12-06 12:00
It seems that it is a problem occurred only once. Maybe the awning is reporting wind. After a couple of minutes the awning started working fine again.

I've also tried to restart the HA in order to check if it is a problem occurred only after a reboot, but it works fine.

I'm closing the issue as it is not a bug of this component.

**Comment by iMicknl** [comment] 2020-12-06 12:44
Could you have a look on TaHomalink.com as well? It should show a message that the device is in lock mode. I did encounter the same for my Pergola when it was around 0 degrees Celsius, due to an automated lock.

Didn’t the icon change to a warning / wind icon in the Home Assistant UI?

**Comment by cdeharo** [comment] 2020-12-07 20:06
Yes, the icon changed to a wind one.
Unfortunately I don't have access to tahomalink.com because I have a Connexoon and not a Tahoma.

**Comment by iMicknl** [comment] 2020-12-07 21:32
@cdeharo if you have any suggestions, let us know. I encountered the same situation this weekend, and didn’t understand at first that it was a hardware lock... We need to better show / log this in UI perhaps.

**Comment by cdeharo** [comment] 2020-12-26 16:30
@iMicknl it happened again today. The awning is closed but after rebooting the HassOS server it detected wind and locked the awning. In the UI it shows the wind icon and the buttons to open/close are disabled.

This time I found a new log:
`2020-12-26 16:43:19 ERROR (MainThread) [custom_components.tahoma] invalid_auth`

Note that my connection credentials haven't changed.

**Current environment:**
* **ha-tahoma version:** 2.3.8
* **Home Assistant version:** 2020.12.1

Nothing else has changed.

15 minutes later, the wind icon still appears and the awning controls are locked.

I tried to use the Connexoon app and it requested a firmware update. After installing the firmware update the Connexoon app worked fine. Then, I rebooted the Home Assistant Core instance only and the awning worked fine again. Later I completly rebooted the HassOS and it continued working.

I don't believe that the firmware update solved the problem, because this problem didn't occurred in ha-tahoma versions older than 2.3.7 and nothing else changed until today (with the Connexoon firmware update).

The `invalid_auth` log didn't appeared in the last two reboots.

**Comment by iMicknl** [comment] 2020-12-26 17:09
Are you able to open / close your awning via the Connexoon app? The lock displayed in Home Assistant is initiated from the TaHoma server. 

What is your polling interval? I will have a look after my vacation to understand if a lock is removed, when the state is updated by TaHoma.

**Comment by cdeharo** [comment] 2020-12-26 17:41
> Are you able to open / close your awning via the Connexoon app? The lock displayed in Home Assistant is initiated from the TaHoma server.

Yes, and it doesn't report wind.

> What is your polling interval?

I haven't set any polling interval in the `tahoma` config section (and did not know that it could be configured):
```yaml
tahoma:
  username: !secret connexoon_username
  password: !secret connexoon_password
```

> I will have a look after my vacation to understand if a lock is removed, when the state is updated by TaHoma.

Tell me if you want me to set any other settings to help going deeper into the problem, but the problem is that I can't reproduce the problem consistently.

Happy Holidays!

**Comment by iMicknl** [comment] 2021-01-08 17:07
I will dig in this a bit deeper, @cdeharo. Did a restart fix your issues? It could be that we don't catch the new state, when the lock is removed by tahomalink.com.

By the way, you are using this integration via the YAML flow, I would advice to configure this integration via the Config Flow. Settings -> Integrations -> +. This is also the page where you can configure some of the settings.

**Comment by iMicknl** [comment] 2021-01-08 17:54
By the way, I discovered that when my device is locked by tahomalink.com, it will remove the "close" button, but it will still show the position buttons.. 

![image](https://user-images.githubusercontent.com/1424596/104047841-98073500-51e2-11eb-8ff4-b47c05771037.png)

**Comment by cdeharo** [comment] 2021-01-17 11:43
> Did a restart fix your issues?

When I opened the bug, only after a restart is when I observed the issue. It solved by itself after a few minutes.
Since my last comment (2020-12-26), the problem has not been reproduced.

> to configure this integration via the Config Flow. Settings -> Integrations -> +

I've deleted the `tahoma` section from the `configuration.yaml` file and restarted the server, but when I try to add the configuration using the Integrations page I receive this error:
`%key:common::config_flow::abort::already_configured_device%`

**Comment by iMicknl** [comment] 2021-01-17 17:41
> I've deleted the `tahoma` section from the `configuration.yaml` file and restarted the server, but when I try to add the _Somfy Tahoma_ using the Integrations page I receive this error:
> `%key:common::config_flow::abort::already_configured_device%`

That is weird... Are you sure there is no mention of `tahoma` in your integrations page? Otherwise we would need to log this as a bug and see if we can reproduce.

> When I opened the bug, only after a restart is when I observed the issue. It solved by itself after a few minutes.
> Since my last comment (2020-12-26), the problem has not been reproduced.

Great to hear! I will close this issue for now, but let us know if you face issues again.

**Closed by iMicknl** 2021-01-17 17:41 UTC
Labels: bug, platform: cover
