### ISSUE TITLE
"Unknown user :" exception when connecting to Somfy Protect account

### ISSUE THREAD

**Issue by asetGem** [iMicknl/ha-tahoma#801] opened 2022-04-10 20:47 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I have a Somfy Home Alarm.
I first tried to install the official Somfy integration in my HA, but it did not work ("quota exceeded" as many others). So, I found this custom component. 

I tried to install it both with HACS and manually, but I always have the same problem:
When I give my login/password, it writes "unknown error happened" and stops (my HA is in French, so the translation might not be the same).
I tried with another email address, and it said "wrong email or password" (as expected). So, when I put my "real" credentials, it finds that this account exists, but then something goes wrong...
Any idea what I could do?

Thanks! 

### What version of this integration (ha-tahoma) has the issue?

Not able to install, so I don't know, but it must be the last one

### What version of Home Assistant Core has the issue?

core-2022.4.1

### Which gateway / hub do you use?

Somfy (Europe)

### Device model

Somfy Home alarm (not recognized by HA as the integration does not work)

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment] 2022-04-10 20:55
Can you please add your logs? And did you try to use the Overkiz integration from core?

You probably don’t need this custom component.

**Comment by asetGem** [comment] 2022-04-10 20:58
Hi! Sorry, I'm new in HA, so I'm not familiar with it.
I do not have logs, because I used the UI to try to install it... 

What do you mean by overkiz from core?

**Comment by asetGem** [comment] 2022-04-10 21:04
I tried these 2 integrations: 
<img src="https://user-images.githubusercontent.com/15121352/162639602-a0b3ad70-8ba3-4af1-b316-413b270ea062.png" data-canonical-src="https://user-images.githubusercontent.com/15121352/162639602-a0b3ad70-8ba3-4af1-b316-413b270ea062.png" width="200" />

But then, when I try to login, I have this "unexpected error":


<img src="https://user-images.githubusercontent.com/15121352/162639656-351d6cc7-751a-4e49-a5c3-83e178400ba1.png" data-canonical-src="https://user-images.githubusercontent.com/15121352/162639656-351d6cc7-751a-4e49-a5c3-83e178400ba1.png" width="200" />

**Comment by iMicknl** [comment] 2022-04-10 21:28
@asetGem can you please share your log? This will help us to understand what error you face.

**Comment by asetGem** [comment] 2022-04-10 21:29
Where can I find this log?

**Comment by iMicknl** [comment] 2022-04-10 21:30
Just your standard Home Asssistant log. Configuration > Settings > Log

Or click here: [![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/).

**Comment by asetGem** [comment] 2022-04-10 21:42
It says `unknown user` in the log. That was not the message on the UI.
But I'm sure about my login and password, I just tried to log out and in in the somfy app :( 
Is it another account?

```
Traceback (most recent call last):
  File "/config/custom_components/tahoma/config_flow.py", line 73, in async_step_user
    await self.async_validate_input(user_input)
  File "/config/custom_components/tahoma/config_flow.py", line 58, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 151, in login
    await self.register_event_listener()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 508, in register_event_listener
    response = await self.__post("events/register")
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 666, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 744, in check_response
    raise Exception(message if message else result)
Exception: Unknown user : 'xxxx'
```

**Comment by asetGem** [comment] 2022-04-10 21:59
I also have a "flexom" account, and I get the same result (same log, but I selected "flexom" instead of "somfy (europe)"

**Comment by iMicknl** [comment] 2022-04-11 07:13
@asetGem thanks! The reason this error does not show up in the UI, is because we have never seen this error before and thus it is not included in your errors yet. (hence you see 'Unexpected Error').

I am also not able to reproduce this error, when I use an unknown account, it will just return 'Invalid Authentication'. Which hub do you own?

Which Somfy (or Flexom) app do you use to control your devices?

**Comment by asetGem** [comment] 2022-04-11 07:52
# somfy

For Somfy, I own a "somfy home alarm", which is composed of:

- somfy siren: https://shop.somfy.co.uk/somfy-wireless-indoor-siren/?int_campaign=merge_cms_shop&int_content=product_listing&int_source=site
- intellitag : https://shop.somfy.co.uk/intellitag/?int_campaign=merge_cms_shop&int_content=product_listing&int_source=site
- motion sensor: https://shop.somfy.co.uk/somfy-protect-motion-sensor/?int_campaign=merge_cms_shop&int_content=product_listing&int_source=site
- key remote : https://shop.somfy.co.uk/somfy-key-fob/?int_campaign=merge_cms_shop&int_content=product_listing&int_source=site
- somfy link (the hub)

I use the "Somfy protect" app to control it.

# flexom

I have a Flexom hub, which is a "Hattara® Rail DIN" with enocean and IO modules.
More info here: https://www.overkiz.com/en/flexom-3-0-connected-homes-by-bouygues-immobilier-and-overkiz/

I use "Flexom v3" app to control my lights and shutters.


Thanks for your help!

**Comment by asetGem** [comment] 2022-04-11 07:56
I tried to connect my somfy system with IFTTT (to try another platform), and it works perfectly.

**Comment by iMicknl** [comment] 2022-04-11 08:55
Thanks! I will need to research if Somfy Protect is even supported, I recall they use a different back-end system and thus cannot be supported in the Overkiz integration. (without using another Overkiz gateway).

Flexom should be supported since a recent update. Can you try the Flexom server again and share your log for this specific case?

**Comment by asetGem** [comment] 2022-04-11 09:13
There is no new log when I try to connect to flexom :( 
Here is the last log entry, but it was yesterday evening: 

```
2022-04-10 22:30:14 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-10 22:30:14 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by iMicknl** [comment] 2022-04-11 09:20
What is the error when you try to login to Flexom? Perhaps we should split your issue in two separate issues (or only handle of them here), since they are not related.

**Comment by asetGem** [comment] 2022-04-11 11:03
I was about to create a second issue for flexom yes. But then, I saw that a new version of HA was released 4 days ago. I updated, and Flexom worked with the overkizz add-on! (So I did not try with the custom component, as the core one already works.) Thus, I don't need to post an issue (or maybe post it and advise to update HA, but not sure it would help somebody).

But, unfortunatelly, somfy still does not work, so this issue is still "alive" :(

**Comment by asetGem** [comment] 2022-04-11 21:57
Thanks for your help! I'll have a look at this!

The weird part is that my account is not a "somfy protect" account. It is a regular Somfy account (somfy.com). I could buy store bannes or whatever, and use them with this same account. 
So, if the integration does not support Somfy protect, I would have expected that it still connects to my account, but just does not detect my equipment after.

**Comment by iMicknl** [comment] 2022-09-03 16:31
Fixed in core!

**Closed by iMicknl** 2022-09-03 16:31 UTC
Labels: bug, blocked
