### ISSUE TITLE
Tahoma "Timeout fetching TaHoma Event Fetcher data"

### ISSUE THREAD

**Issue by Tonylolo** [iMicknl/ha-tahoma#344] opened 2021-01-14 20:23 UTC
- [ ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
it's random, sometimes daily, sometimes 3 times a week ... the controls for my shutters for my tahoma do not work.
In the log I have the message: Timeout fetching TaHoma Event Fetcher data.

After restarting the server, everything works again.

I am using HA on container / Qnap.

**To Reproduce**

Just wait several minutes or hours...and in my log I have:

Timeout fetching TaHoma Event Fetcher data

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- **ha-tahoma version:** lastest
- **Home Assistant version:** Home Assistant 2020.12.1
- **Platform**: [e.g. cover, sensor, binary_sensor]
roller
**Device:** (if your problem is related to a specific device)
Tahoma
- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: [e.g. `io:DimmableLightIOComponent`, can be gathered from device page in HA looking at Firmware] `/config/devices/dashboard`]

**Additional context**

**Comment by iMicknl** [comment] 2021-01-14 20:36
Duplicate of #345.

**Closed by iMicknl** 2021-01-14 20:36 UTC
Labels: bug
