### ISSUE TITLE
RTS awning no longer available

### ISSUE THREAD

**Issue by golles** [iMicknl/ha-tahoma#462] opened 2021-06-28 07:59 UTC
- [ ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
Every 30 seconds I'm seeing an `ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last)`. I noticed this morning that I had 45k entries in the logfile and HA was restarted yesterday.
I did see this log for a few days and decided to update my TaHoma box, that had no result.

**To Reproduce**
(Re)start HA

**Expected behavior**
No errors

**Logs**
I've redacted some (unique?) numbers/id's, if it helps I can still provide those.
```yaml
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Initialized DataUpdateCoordinator with 0:00:30 interval.
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.031 seconds
2021-06-28 09:41:43 INFO (MainThread) [custom_components.tahoma] HomeKit support detected with setup code 034-18-406.
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Added device (internal:TSKAlarmComponent - Alarm - TSKAlarmController - internal://xxxx-yyyy-zzzz/alarm/0)
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Added device (io:RollerShutterGenericIOComponent - RollerShutter - PositionableRollerShutter - io://xxxx-yyyy-zzzz/redacted)
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Added device (io:RollerShutterGenericIOComponent - RollerShutter - PositionableRollerShutter - io://xxxx-yyyy-zzzz/redacted)
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (rtds:RTDSRemoteControllerComponent - RemoteController - AlarmRemoteController - rtds://xxxx-yyyy-zzzz/redacted)
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Added device (rts:HorizontalAwningRTSComponent - Awning - UpDownHorizontalAwning - rts://xxxx-yyyy-zzzz/redacted)
2021-06-28 09:41:43 DEBUG (MainThread) [custom_components.tahoma] Added gateway (xxxx-yyyy-zzzz - GatewayType.TAHOMA_V2 - GatewaySubType.TAHOMA_SHORT_CHANNEL)
2021-06-28 09:41:43 ERROR (MainThread) [homeassistant.components.cover] Error adding entities for domain cover with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 187, in state
    if self.is_opening:
  File "/config/custom_components/tahoma/cover.py", line 327, in is_opening
    is_moving = self.device.states[CORE_MOVING_STATE].value
TypeError: 'NoneType' object is not subscriptable
```
The trace part is repeating every 30sec.

**Environment (please complete the following information):**

- **Hub**: TaHoma 2021.2.4-12
- **ha-tahoma version:** master
- **Home Assistant version:** 2021.6.6
- **Platform**: cover

**Device:** Not sure from the logs,

- **Model**: UpDownHorizontalAwning
- **Type**: rts:HorizontalAwningRTSComponent
**Additional context**

**Comment by golles** [comment] 2021-06-28 08:01
I know I've not followed up on #439, but I don't think it's related. Beside that again the RTS devices broke.
Let me know what I can do to help?

**Comment by iMicknl** [comment] 2021-06-28 21:19
Thanks for reporting, this seems caused by https://github.com/iMicknl/ha-tahoma/pull/460.

For now, I would advise to upgrade to the previous version, until someone has time to implement a fix! 👍🏻

**Comment by tetienne** [comment] 2021-06-28 21:36
Indeed my bad. I missed this case. Should be fixed tomorrow!

**Comment by golles** [comment] 2021-06-28 22:33
I also have a trace when closing IO shutter
```yaml
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/cover.py", line 253, in async_close_cover
    await self.async_execute_command(self.select_command(*COMMANDS_CLOSE))
  File "/config/custom_components/tahoma/tahoma_entity.py", line 183, in async_execute_command
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 187, in state
    if self.is_opening:
  File "/config/custom_components/tahoma/cover.py", line 327, in is_opening
    is_moving = self.device.states[CORE_MOVING_STATE].value
TypeError: 'NoneType' object is not subscriptable
```
I guess the same issue, but wanted to share if now

**Comment by iMicknl** [comment] 2021-06-29 15:45
@golles, latest master branch should fix your issues!

**Comment by golles** [comment] 2021-06-30 08:17
Updated and the same issue

```
2021-06-30 10:12:18 ERROR (MainThread) [homeassistant.components.cover] Error adding entities for domain cover with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 187, in state
    if self.is_opening:
  File "/config/custom_components/tahoma/cover.py", line 327, in is_opening
    is_moving = self.device.states.get(CORE_MOVING_STATE)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by iMicknl** [comment] 2021-06-30 08:20
Thanks, I see where the issue is. @tetienne seems that we forgot that states is optional and that RTS covers don't have states available..

**Comment by tetienne** [comment] 2021-07-01 07:32
My bad, I was sure the returned `states` was empty for RTS devices.

**Comment by golles** [comment] 2021-07-10 09:28
I'm on the branch `fix/rts/moving_cover_2` now for a couple of days and all seem to work fine, no errors in my logs, and awning and shutters seem to work

**Closed** 2021-07-14 17:09 UTC
Labels: bug
