### ISSUE TITLE
Add support for Tahoma Somfy Remote controller (rtds:RTDSRemoteControllerComponent)

### ISSUE THREAD

**Issue by LoicRivoal** [iMicknl/ha-tahoma#305] opened 2020-10-25 09:41 UTC
**Device information**
The Somfy Remote Controller 5 buttons shipped and paired with the Tahoma box is not recognized.
would it be possible to associate the Remote Controller buttons to scenes/scripts in HA ?

**Device details**
2020-10-25 10:23:48 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rtds:RTDSRemoteControllerComponent - RemoteController - AlarmRemoteController)

**Comment by tetienne** [comment] 2020-10-25 11:14
Duplicate of #259.

**Closed by tetienne** 2020-10-25 11:14 UTC
Labels: new-device

**Comment by iMicknl** [comment] 2020-10-25 12:00
@LoicRivoal feel free to do a thumbs up 👍🏻 on #259 or add additional information you miss in that issue.

Thanks for reporting!
