### ISSUE TITLE
Add support for Thermor Equateur 3 - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint (io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent)

### ISSUE THREAD

**Issue by browetd** [iMicknl/ha-tahoma#339] opened 2021-01-13 16:16 UTC
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Device information**
Thermor "Equateur 3" electrical heaters, they are partially discovered (binary sensors: occupancy and contact, sensors: temperature and cumulative electric power consumption as well as some scenes to change target temperature).
But no climate entity created for that device.  I am using the Cozytouch Bridge (not the Tahoma Box).
(io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint)

**Device details**
(io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint)

```
`2021-01-13 14:20:35 DEBUG (MainThread) [custom_components.tahoma.coordinator] Initialized DataUpdateCoordinator with 0:00:30 interval.
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.109 seconds
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint - io://0806-0588-9588/12338497#1)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:TemperatureInCelciusIOSystemDeviceSensor - TemperatureSensor - TemperatureSensor - io://0806-0588-9588/12338497#2)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:ContactIOSystemDeviceSensor - ContactSensor - ContactSensor - io://0806-0588-9588/12338497#3)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:OccupancyIOSystemDeviceSensor - OccupancySensor - OccupancySensor - io://0806-0588-9588/12338497#4)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:CumulatedElectricalEnergyConsumptionIOSystemDeviceSensor - ElectricitySensor - CumulativeElectricPowerConsumptionSensor - io://0806-0588-9588/12338497#5)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint - io://0806-0588-9588/15461267#1)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:TemperatureInCelciusIOSystemDeviceSensor - TemperatureSensor - TemperatureSensor - io://0806-0588-9588/15461267#2)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:ContactIOSystemDeviceSensor - ContactSensor - ContactSensor - io://0806-0588-9588/15461267#3)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:OccupancyIOSystemDeviceSensor - OccupancySensor - OccupancySensor - io://0806-0588-9588/15461267#4)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:CumulatedElectricalEnergyConsumptionIOSystemDeviceSensor - ElectricitySensor - CumulativeElectricPowerConsumptionSensor - io://0806-0588-9588/15461267#5)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint - io://0806-0588-9588/8228744#1)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:TemperatureInCelciusIOSystemDeviceSensor - TemperatureSensor - TemperatureSensor - io://0806-0588-9588/8228744#2)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:ContactIOSystemDeviceSensor - ContactSensor - ContactSensor - io://0806-0588-9588/8228744#3)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:OccupancyIOSystemDeviceSensor - OccupancySensor - OccupancySensor - io://0806-0588-9588/8228744#4)
2021-01-13 14:20:36 DEBUG (MainThread) [custom_components.tahoma] Added TaHoma device (io:CumulatedElectricalEnergyConsumptionIOSystemDeviceSensor - ElectricitySensor - CumulativeElectricPowerConsumptionSensor - io://0806-0588-9588/8228744#5)
2021-01-13 14:21:06 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.063 seconds
2021-01-13 14:21:36 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.062 seconds
```

![Sans titre_6](https://user-images.githubusercontent.com/46415133/104478823-08d39600-55c3-11eb-9d0e-2a12e16c2d1f.png)
![Sans titre_5](https://user-images.githubusercontent.com/46415133/104478826-096c2c80-55c3-11eb-86ec-6b2f7e60673e.png)
![Sans titre_4](https://user-images.githubusercontent.com/46415133/104478827-096c2c80-55c3-11eb-90a8-356e3e8fdbbd.png)
![Sans titre_3](https://user-images.githubusercontent.com/46415133/104478832-0a04c300-55c3-11eb-8074-89e648836038.png)
![Sans titre_2](https://user-images.githubusercontent.com/46415133/104478834-0a04c300-55c3-11eb-9e53-098d69f908c7.png)
![Sans titre_1](https://user-images.githubusercontent.com/46415133/104478836-0a04c300-55c3-11eb-8240-1089c1af7af4.png)

**Comment by iMicknl** [comment] 2021-01-13 20:02
Thanks for reporting, @browetd! It looks like a duplicate of https://github.com/iMicknl/ha-tahoma/issues/304. I will try to see if I can add support for this device in the coming days.

**Comment by browetd** [comment] 2021-01-13 21:36
It would be great !  Thanks !

**Comment by iMicknl** [comment] 2021-01-27 14:04
Tracked in #304.

**Closed by iMicknl** 2021-01-27 14:04 UTC
Labels: new-device, platform: climate
