### ISSUE TITLE
Cover position is reversed for AwningValance

### ISSUE THREAD

**Issue by inconsx** [iMicknl/ha-tahoma#292] opened 2020-10-08 12:13 UTC
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Is your feature request related to a problem? Please describe.**
If cover 'volant' of my  awning is is closed the entity card shows that as open and the other way around.
This behavior is different than for other covers like 'Raffstores'

**Describe the solution you'd like**
If the volant is closed display the status as 'closed' and the other way around

Thanks!
![tahoma_volant](https://user-images.githubusercontent.com/22166678/95456974-780c6f00-0970-11eb-8b43-096b0b65c6ed.jpg)
![HA_volant](https://user-images.githubusercontent.com/22166678/95456981-7a6ec900-0970-11eb-81c0-d73291f34a0a.jpg)

**Comment by vlebourl** [comment] 2020-10-08 12:18
Thank you for reporting this issue. Can you please provide us with `ui_class`, `widget` and `controllable_name` of your device? This is available in the /developer-tools/state page of your Home Assistant.

**Comment by iMicknl** [comment] 2020-10-08 12:28
Could you please provide us with the firmware version of your TaHoma / Connexoon bridge as well? You can find that on tahomalink.com.

I have seen this issue arise on https://github.com/dubocr/homebridge-tahoma/issues/206 as well. It looks like Somfy finally standardized the Horizontal Awning devices, which we had to reverse manually in the code...

**Comment by inconsx** [comment] 2020-10-08 12:36
Code of my Entity Card:
entities:
  - entity: cover.volant
    name: Volant
    type: 'custom:slider-entity-row'
title: Covers
type: entities
theme: Google Dark Theme
tahoma FW: 2020.4.4-18

Can I do here anything on my own?

**Comment by vlebourl** [comment] 2020-10-08 12:40
Thanks, but this is not the info we would need (aside from the TaHoma firmware). 
In the State tab of the developper tools, type the name of your entity in the head of the first column, and you should see something like this
![image](https://user-images.githubusercontent.com/5701372/95459601-31207880-0974-11eb-84be-cc1fac00a46f.png)
We would need the content of the third column.

**Comment by vlebourl** [comment] 2020-10-08 12:46
can you confirm that current_position: 100 is fully closed in your case?

**Comment by inconsx** [comment] 2020-10-08 12:51
> can you confirm that current_position: 100 is fully closed in your case?

Yes, I can confirm

**Comment by vlebourl** [comment] 2020-10-08 12:52
can you give this a try? uncompress the zip, replace your custom_components/tahoma folder with the one in the zip and restart HA.
https://github.com/iMicknl/ha-tahoma/archive/fix/ha-tahoma-292.zip

**Comment by inconsx** [comment] 2020-10-08 13:41
> can you give this a try? uncompress the zip, replace your custom_components/tahoma folder with the one in the zip and restart HA.
> https://github.com/iMicknl/ha-tahoma/archive/fix/ha-tahoma-292.zip

tested successfully: volant is fully closed 
Status:
![image](https://user-images.githubusercontent.com/22166678/95466193-603ae800-097c-11eb-9432-a66e9e21949e.png)

Can you add this percentage indicator to the following main awning as well?
entity: cover.markise

current_position: 0
ui_class: Awning
widget: PositionableHorizontalAwning
controllable_name: 'io:HorizontalAwningIOComponent'
rssi_level: 46
'core:NameState': Markise
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': normal
'core:RSSILevelState': 46
'core:DeploymentState': 0
'core:OpenClosedState': closed
'core:Memorized1PositionState': 105
'core:TargetClosureState': 0
friendly_name: Markise
supported_features: 527
device_class: awning

Thanks

**Comment by iMicknl** [comment] 2020-10-08 16:54
@inconsx could you create a new issue for your `PositionableHorizontalAwning`? This one should already be working correctly, thus we need to investigate if this is caused by the update and if this issue is present for all 'Awning' devices.

**Closed** 2020-10-25 14:01 UTC
Labels: bug, platform: cover
