### ISSUE TITLE
not working since 2011.0

### ISSUE THREAD

**Issue by standu2186** [iMicknl/ha-tahoma#826] opened 2022-11-04 07:26 UTC
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

hello team,

the module no longer works since version 2011.0

### What version of this integration (ha-tahoma) has the issue?

2.13

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Interface utilisateur : 20221102.1 - latest

### Which gateway / hub do you use?

Somfy Connectivity Kit

### Home Assistant log

<details><summary>Logs</summary>

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 08:07:00 (3 occurrences)
Last logged: 08:07:15

Unable to install package pyoverkiz==1.3.6: ERROR: Cannot install pyoverkiz==1.3.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.1 -> 22.3 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:184
First occurred: 08:07:15 (1 occurrences)
Last logged: 08:07:15

Setup failed for custom integration tahoma: Requirements for tahoma not found: ['pyoverkiz==1.3.6'].

</details>

**Comment by ckd77** [comment] 2022-11-04 07:57
Me too, same problem. So I restored a backup of ha while waiting for a correction.

**Comment by iMicknl** [comment] 2022-11-04 08:18
Duplicate of #824.

**Closed by iMicknl** 2022-11-04 08:18 UTC
Labels: bug
