### ISSUE TITLE
Open/Close Status indicator (percentage) inconsistency  - AwningValance (io:AwningValanceIOComponent)

### ISSUE THREAD

**Issue by inconsx** [iMicknl/ha-tahoma#351] opened 2021-01-18 12:50 UTC
- [x ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
percentage indicatory is not consistent overy the somfy products

**To Reproduce**
configure entity in entity card

**Expected behavior**
same status indicator in percentage for every somfy cover product

**Screenshots**
![image](https://user-images.githubusercontent.com/22166678/104917249-74d34700-5993-11eb-8ada-58065c63d80e.png)

**Environment (please complete the following information):**

- **ha-tahoma version:** 2020.6.4-15
- **Home Assistant version:** core-2021.1.4
- **Platform**: cover.volant

**Device:** (if your problem is related to a specific device)
pc

- **Model**: 
current_position: 0
ui_class: Awning
widget: AwningValance
controllable_name: 'io:AwningValanceIOComponent'
rssi_level: 32
'core:NameState': Volant
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': low
'core:RSSILevelState': 32
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
friendly_name: Volant
supported_features: 527
device_class: awning

- **Type**: controllable_name: 'io:AwningValanceIOComponent'

**Additional context**

**Comment by iMicknl** [comment] 2021-01-19 19:34
Thanks for reporting @inconsx. It seems that there is an issue in the latest version of ha-tahoma or changes have been made on the side of Somfy TaHoma... 

We have had these issues in the past as well, however when we reverse the state, someone else will have issues with exactly the same device. We need to investigate more, will let you know when I do require more details.

Do you know the type (TaHoma vs Connexoon) of your hub and the firmware version of your hub? And just to double check, the status on tahomalink.com is correct?

(possible duplicate of #352 and #350)

**Comment by inconsx** [comment] 2021-01-19 20:39
Hey

It's a Tahoma and the firmware is 2.18.
Status is correct. 

Thanks and regards

**Comment by iMicknl** [comment] 2021-02-03 23:09
Could you give https://github.com/iMicknl/ha-tahoma/archive/fix/awning_valance.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder. This should solve your issues.

**Comment by inconsx** [comment] 2021-02-12 09:56
Hi,

can we reopen this issue. 
Volant is now 90 % open but is shown 10% open

![image](https://user-images.githubusercontent.com/22166678/107753363-45a8bf00-6d20-11eb-9447-fdb56317ffa8.png)
![image](https://user-images.githubusercontent.com/22166678/107753444-5d804300-6d20-11eb-970e-49e165e24f6d.png)

Tahoma FW: 2.19
Home Assistant 2021.2.3

current_position: 12
rssi_level: 38
'core:NameState': Volant
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': low
'core:RSSILevelState': 38
'core:ClosureState': 88
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
friendly_name: Volant
supported_features: 527
device_class: awning

**Comment by iMicknl** [comment] 2021-02-12 09:58
@inconsx which version of the TaHoma integration are you using?

**Comment by inconsx** [comment] 2021-02-12 10:38
@iMicknl 

2.4.7

**Comment by iMicknl** [comment] 2021-02-12 10:47
@inconsx this fix has been confirmed with others with the same device.. Perhaps there are even differences between the same devices.

Do all buttons work? (open / close / set position). I would like to understand if this is just a cosmetic issue or if this disables the functionality.

**Comment by inconsx** [comment] 2021-02-12 19:35
@iMicknl 
every button is working, yes.
it's just inverted and it's the only entity which shows percentage indicator when closed (before 0% and now inverted 100%)
![image](https://user-images.githubusercontent.com/22166678/107814161-ca6ff900-6d71-11eb-8a41-96b46f9d4c75.png)

**Closed** 2021-04-03 01:51 UTC
Labels: bug, bug: reversed state, no-issue-activity

**Comment by labr3y** [comment] 2021-04-10 16:39
Hello,

I've got the same issue. It's been like since the start (about 1 year ago).
Beside the awning, all other Somfy equipment report the correct states in HA.

I went through several Tahoma firmwares and several Home Assistant releases, and no improvement as been seen.

Currently I'm on these releases : 
Tahoma firmware : 2021.1.4-12
Home Assistant : docker 2021.4.3
HA Tahoma : 2.4.8

Below, on the screenshots, you can see the awning is reported to be open when it's actually closed (Tahoma on android or tahomalink.com show me the correct status). I can still use the HA Tahoma integration to open or close the awning, but I have to know that the numbers and status are incorrect.

![image](https://user-images.githubusercontent.com/73796206/114277116-2aa9b100-9a2a-11eb-8643-a4ce3d8441b0.png)

![image](https://user-images.githubusercontent.com/73796206/114277159-575dc880-9a2a-11eb-826b-0881d49e7b54.png)

**Comment by iMicknl** [comment] 2021-04-13 12:57
@labr3ythank, I would like to see if I can tackle this issue this week. Is anyone willing to work with me via Discord to see if we can debug / fix this issue? Would be great to have this solved before the integration is added to core.

Join us on Discord (https://discord.gg/3Wpn6q9z or add iMick#1903, to discuss in more detail. Eventually the easiest would be if you are able to change your password temporarily and share your credentials privately, so I can have a quick look and see how to fix it :).

**Comment by labr3y** [comment] 2021-04-13 13:11
I could help with that. I'll try to join you later on discord after work. We can see how and when we can do some testing.
